version: '3'

services:

    node:
        build: .docker/node
        image: nodealp
        container_name: site
        volumes:
            - .:/var/www
        ports:
            - 3000
        networks:
          - app-network


networks:
    app-network:
        driver: bridge
